image:
  repository: ttl.sh/dr-platform-agent
  tag: 24h
  pullPolicy: Always

agent:
  platformUrl: ""
  clusterId: user-k8s
  token: ""
  pollInterval: 30000
  restorePollInterval: 5000
  restorePollAttempts: 36

serviceAccount:
  create: true
  name: ""

resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 250m
    memory: 256Mi
